### PR TITLE
Update vector.md

### PR DESCRIPTION
**Pull request by hev**
A few clarifications and details. I'd also recommend the help text itself be updated to state things are vector specific, and also that we not use the default cluster_name dc.

### CODE REVIEW

**Comment by hev** [comment]
A few more things to note.

Question
* Is there a way to upload multiple files? THis step is kind of clunky but maybe we could add some commands to zip and upload.

Nice to have
* It would be nice to just pre-install examples
* Instructions to add to monitoring stack also nice to have

**Comment by hev** [comment]
I am also getting this when I try to upload

```
➜  deploy_clients git:(vector-readme-updates) aerolab files upload -c -n vector  /Users/ahevenor/Downloads/IMG_1242.jpg /opt/proximus-examples/prism-image-search/prism/static/images/data/
2024/04/02 09:15:05 -0600 Running files.upload
2024/04/02 09:15:05 -0600 ERROR SRC=vector:1 MSG=exit status 1: no such directory;
2024/04/02 09:15:05 -0600 Don
```

**Comment by hev** [comment]
And finally, I got things uploaded and ran the start command but I am not sure where to access it. Nothing served at http://127.0.0.1:8998/ or http://127.0.0.1:8080/

**Comment by robertglonek** [comment]
@hev 

> A few clarifications and details. I'd also recommend the help text itself be updated to state things are vector specific, and also that we not use the default cluster_name dc.

Yes, I will update the help message contents in the source and this doc to reflect what is configuring what.

> Is there a way to upload multiple files? THis step is kind of clunky but maybe we could add some commands to zip and upload.

Yes, the `files upload` command allows to specify a directory as opposed to single files.

> It would be nice to just pre-install examples

I have considered it, but decided against it. The reason is simple - examples are HUGE, especially the prism one. The actual install of the whole proximus is under 300MiB, including java itself. It also takes only a minute of actual install time. The install of prism example alone is 1.2GiB and takes a very long time. I felt providing instructions and scripts may be a better way to provide a smooth experience. Having said that, this is open for discussion if you think we can somehow make this smoother.

> Instructions to add to monitoring stack also nice to have

I can add the relevant switches to enable this, just like with graph. Can you provide me with a snippet of the relevant prometheus yaml file example on how to configure it to the correct URL for monitoring?

> I am also getting this when I try to upload

Did you run the prism install script before trying to upload?

> And finally, I got things uploaded and ran the start command but I am not sure where to access it. Nothing served at http://127.0.0.1:8998/ or http://127.0.0.1:8080/

Is it docker/GCP/AWS you are deploying in? If Cloud, you need to use the http://EXTERNAL_IP:8080. If docker, you need to use http://127.0.0.1:8998, unless you have made some changes to a few aerolab features like `NoAutoExpose`. Can you provide output of `aerolab client list` as well as `aerolab config backend`? Did you keep the prism script running or did you CTRL+C it and not start it after?

**Comment by hev** [comment]
> I have considered it, but decided against it. The reason is simple - examples are HUGE, especially the prism one.

Good point.

> Did you run the prism install script before trying to upload?

Yes, but it looks like something happened.

```shell
➜  deploy_clients git:(vector-readme-updates) aerolab client attach -n vector -- /bin/bash /opt/prism-example.sh
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.10).
python3 is already the newest version (3.10.6-1~22.04).
python3-pip is already the newest version (22.0.2+dfsg-1ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 16 not upgraded.
fatal: destination path 'proximus-examples' already exists and is not an empty directory.
2024/04/02 09:19:01 -0600 exit status 128
```

> Can you provide me with a snippet of the relevant prometheus yaml file example on how to configure it to the correct URL for monitoring?

Yes. We do it here: https://github.com/citrusleaf/proximus-sandbox/blob/main/new-trial.sh

> Is it docker/GCP/AWS you are deploying in? 

Testing on docker atm. It appears this is due to the prism script problem I am guessing.

**Comment by robertglonek** [comment]
I am going to move the conversation out of the pull request.

**Pull request merged**
